"""
Seed database with comprehensive intervention library
Run: python seed_interventions.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.core.database import SessionLocal, engine, Base
from app.models.intervention import Intervention

# Create tables
Base.metadata.create_all(bind=engine)

# Comprehensive intervention library
INTERVENTIONS = [
    # DBT (Dialectical Behavior Therapy) - 30 interventions
    {
        "name": "Box Breathing",
        "short_description": "Calm your nervous system with 4-count breathing",
        "detailed_instructions": "1. Breathe in slowly for 4 counts\n2. Hold your breath for 4 counts\n3. Breathe out slowly for 4 counts\n4. Hold for 4 counts\n5. Repeat 4-6 times",
        "duration_seconds": 120,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["anxiety", "stress", "panic", "overwhelm"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "TIPP - Temperature",
        "short_description": "Use cold to rapidly reduce intense emotions",
        "detailed_instructions": "Hold ice cubes in your hands, splash very cold water on your face, or place a cold pack on your neck. The cold activates your dive reflex, which slows your heart rate and calms your system. Hold for 30-60 seconds.",
        "duration_seconds": 60,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "DBT",
        "sub_category": "TIPP Skills",
        "target_emotions": ["rage", "panic", "intense_anxiety", "crisis"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "DBT Skills Training",
        "evidence_strength": "strong"
    },
    {
        "name": "TIPP - Intense Exercise",
        "short_description": "Quick burst of exercise to change body chemistry",
        "detailed_instructions": "Do 1-2 minutes of intense exercise: jumping jacks, running in place, burpees, or climbing stairs rapidly. The goal is to get your heart rate up quickly to shift your emotional state.",
        "duration_seconds": 120,
        "effort_level": "high",
        "energy_required": "high",
        "therapeutic_approach": "DBT",
        "sub_category": "TIPP Skills",
        "target_emotions": ["anger", "anxiety", "restlessness", "panic"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "high",
        "requires_movement": True,
        "evidence_source": "DBT Skills Training",
        "evidence_strength": "strong"
    },
    {
        "name": "TIPP - Paced Breathing",
        "short_description": "Slow breathing to activate parasympathetic nervous system",
        "detailed_instructions": "Breathe out slowly, making your exhale longer than your inhale. Try breathing in for 4 counts and out for 6-8 counts. Continue for 2-3 minutes.",
        "duration_seconds": 180,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "DBT",
        "sub_category": "TIPP Skills",
        "target_emotions": ["anxiety", "panic", "stress"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Training",
        "evidence_strength": "strong"
    },
    {
        "name": "Opposite Action",
        "short_description": "Act opposite to your emotion urge",
        "detailed_instructions": "Identify what your emotion is urging you to do, then do the opposite. Example: If sad and wanting to isolate, reach out to someone instead. If angry and wanting to attack, be gentle instead.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "DBT",
        "sub_category": "Emotion Regulation",
        "target_emotions": ["sadness", "anger", "fear", "shame"],
        "adhd_friendly": True,
        "asd_friendly": False,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "Radical Acceptance",
        "short_description": "Accept reality as it is without judgment",
        "detailed_instructions": "Acknowledge that this is the current reality. Say to yourself: 'This is happening, and fighting against reality causes more suffering.' Accept fully with your whole self. Let go of bitterness.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["frustration", "anger", "disappointment", "grief"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "Half-Smile",
        "short_description": "Gentle smile to shift emotional state",
        "detailed_instructions": "Relax your face. Turn the corners of your lips up slightly—just enough so you feel it. Relax your forehead, eyes, and jaw. Keep this half-smile for 1-2 minutes while breathing slowly.",
        "duration_seconds": 120,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "DBT",
        "sub_category": "Mindfulness",
        "target_emotions": ["sadness", "anger", "irritation"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "moderate"
    },
    {
        "name": "STOP Skill",
        "short_description": "Stop, Take a step back, Observe, Proceed mindfully",
        "detailed_instructions": "S - Stop what you're doing\nT - Take a step back from the situation\nO - Observe what's happening inside and outside you\nP - Proceed mindfully with awareness",
        "duration_seconds": 60,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["impulsivity", "anger", "anxiety", "overwhelm"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "Self-Soothe with 5 Senses",
        "short_description": "Comfort yourself using each of your senses",
        "detailed_instructions": "Choose one sense at a time:\n- Vision: Look at something beautiful\n- Sound: Listen to soothing music\n- Smell: Use a pleasant scent\n- Taste: Eat something you enjoy slowly\n- Touch: Hold something comforting",
        "duration_seconds": 600,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["sadness", "loneliness", "anxiety", "stress"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "IMPROVE the Moment",
        "short_description": "Use imagery, meaning, prayer, relaxation",
        "detailed_instructions": "I - Imagery (imagine a peaceful place)\nM - Meaning (find purpose in the situation)\nP - Prayer or meditation\nR - Relaxation (relax your muscles)\nO - One thing at a time\nV - Vacation (brief mental break)\nE - Encouragement (cheer yourself on)",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["overwhelm", "hopelessness", "stress"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "Pros and Cons List",
        "short_description": "Weigh options before acting on urges",
        "detailed_instructions": "Create a list with 4 sections:\n1. Pros of acting on urge\n2. Cons of acting on urge\n3. Pros of resisting urge\n4. Cons of resisting urge\nReview to make wise mind decision.",
        "duration_seconds": 600,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "DBT",
        "sub_category": "Distress Tolerance",
        "target_emotions": ["impulsivity", "cravings", "urges"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },
    {
        "name": "Check the Facts",
        "short_description": "Examine if your emotion fits the facts",
        "detailed_instructions": "Ask yourself:\n1. What is the emotion I want to change?\n2. What is the event that triggered it?\n3. What are my interpretations?\n4. Am I assuming a threat?\n5. What's the catastrophe?\n6. Does my emotion fit the facts?",
        "duration_seconds": 480,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "DBT",
        "sub_category": "Emotion Regulation",
        "target_emotions": ["anxiety", "anger", "fear", "jealousy"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "DBT Skills Manual",
        "evidence_strength": "strong"
    },

    # ACT (Acceptance and Commitment Therapy) - 20 interventions
    {
        "name": "Leaves on a Stream",
        "short_description": "Watch your thoughts float away like leaves",
        "detailed_instructions": "Imagine sitting by a stream with leaves floating by. Place each thought that arises onto a leaf and watch it float away downstream. Don't try to control or judge the thoughts. Let them come and go.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "ACT",
        "sub_category": "Defusion",
        "target_emotions": ["anxiety", "rumination", "overthinking"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ACT Made Simple",
        "evidence_strength": "strong"
    },
    {
        "name": "Name the Story",
        "short_description": "Give your recurring thought pattern a name",
        "detailed_instructions": "Notice a recurring unhelpful thought pattern. Give it a name like 'The I'm not good enough story' or 'The catastrophe story'. When it appears, say 'Oh, there's that story again' and let it be.",
        "duration_seconds": 180,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "ACT",
        "sub_category": "Defusion",
        "target_emotions": ["negative_self_talk", "rumination", "anxiety"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ACT Made Simple",
        "evidence_strength": "moderate"
    },
    {
        "name": "Thanking Your Mind",
        "short_description": "Thank your mind for unhelpful thoughts",
        "detailed_instructions": "When you notice an unhelpful thought, say 'Thank you mind for that thought' or 'Thanks for trying to protect me'. This creates distance between you and the thought without fighting it.",
        "duration_seconds": 60,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "ACT",
        "sub_category": "Defusion",
        "target_emotions": ["anxiety", "self_criticism", "worry"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "The Happiness Trap",
        "evidence_strength": "moderate"
    },
    {
        "name": "Values Compass Check",
        "short_description": "Reconnect with what matters most to you",
        "detailed_instructions": "Ask yourself: 'What kind of person do I want to be right now?' 'What values do I want to act on?' 'What small step can I take towards those values?' Choose one small action aligned with your values.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "ACT",
        "sub_category": "Values",
        "target_emotions": ["lost", "unmotivated", "disconnected", "stuck"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ACT Made Simple",
        "evidence_strength": "strong"
    },
    {
        "name": "Drop the Anchor",
        "short_description": "Ground yourself in the present moment",
        "detailed_instructions": "A - Acknowledge your thoughts and feelings\nC - Come back into your body (push feet into floor)\nE - Engage in what you're doing (look around, notice 5 things)\nStay anchored while the emotional storm passes.",
        "duration_seconds": 180,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "ACT",
        "sub_category": "Present Moment",
        "target_emotions": ["overwhelm", "panic", "dissociation", "anxiety"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ACT Made Simple",
        "evidence_strength": "strong"
    },
    {
        "name": "The Observing Self",
        "short_description": "Connect with the part of you that observes",
        "detailed_instructions": "Notice your thoughts, feelings, and sensations. Then notice that there's a part of you observing all of this. This observer has been there your whole life. Rest in this observing awareness.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "ACT",
        "sub_category": "Self as Context",
        "target_emotions": ["identity_confusion", "overwhelm", "emotional_flooding"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ACT Made Simple",
        "evidence_strength": "moderate"
    },
    {
        "name": "Expansion Breathing",
        "short_description": "Make room for difficult feelings",
        "detailed_instructions": "Locate where you feel the difficult emotion in your body. Breathe into that area, imagining you're making room around it. Don't try to change or get rid of it. Just make space for it to be there.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "ACT",
        "sub_category": "Acceptance",
        "target_emotions": ["anxiety", "sadness", "grief", "fear"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "The Happiness Trap",
        "evidence_strength": "moderate"
    },
    {
        "name": "I Notice I'm Having the Thought",
        "short_description": "Create distance from thoughts by naming them",
        "detailed_instructions": "Instead of thinking 'I'm worthless', say 'I notice I'm having the thought that I'm worthless'. This creates psychological distance between you and your thoughts. Practice with any recurring thought.",
        "duration_seconds": 120,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "ACT",
        "sub_category": "Defusion",
        "target_emotions": ["self_criticism", "negative_thoughts", "anxiety"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "The Happiness Trap",
        "evidence_strength": "strong"
    },

    # CBT (Cognitive Behavioral Therapy) - 20 interventions
    {
        "name": "5-4-3-2-1 Grounding",
        "short_description": "Use your senses to ground in the present",
        "detailed_instructions": "Name:\n5 things you can see\n4 things you can touch\n3 things you can hear\n2 things you can smell\n1 thing you can taste\nTake your time with each sense.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "CBT",
        "sub_category": "Grounding",
        "target_emotions": ["anxiety", "panic", "dissociation", "overwhelm"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "CBT for Anxiety",
        "evidence_strength": "strong"
    },
    {
        "name": "Thought Record",
        "short_description": "Challenge and reframe negative thoughts",
        "detailed_instructions": "Write down:\n1. Situation (what happened)\n2. Automatic thought (what you thought)\n3. Emotion (how you felt)\n4. Evidence for the thought\n5. Evidence against the thought\n6. Balanced thought",
        "duration_seconds": 600,
        "effort_level": "high",
        "energy_required": "high",
        "therapeutic_approach": "CBT",
        "sub_category": "Cognitive Restructuring",
        "target_emotions": ["depression", "anxiety", "negative_thinking"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Mind Over Mood",
        "evidence_strength": "strong"
    },
    {
        "name": "Cognitive Distortion Identifier",
        "short_description": "Identify thinking errors in your thoughts",
        "detailed_instructions": "Review common distortions:\n- All-or-nothing thinking\n- Catastrophizing\n- Mind reading\n- Fortune telling\n- Emotional reasoning\n- Should statements\nIdentify which ones apply to your current thought.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "CBT",
        "sub_category": "Cognitive Restructuring",
        "target_emotions": ["anxiety", "depression", "worry"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Feeling Good",
        "evidence_strength": "strong"
    },
    {
        "name": "Behavioral Activation",
        "short_description": "Schedule one small pleasurable activity",
        "detailed_instructions": "Choose one small activity that used to bring you joy or that aligns with your values. Schedule it for today. It doesn't have to be big - even 5 minutes counts. Then do it, regardless of how you feel.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "CBT",
        "sub_category": "Behavioral Activation",
        "target_emotions": ["depression", "apathy", "low_motivation"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "CBT for Depression",
        "evidence_strength": "strong"
    },
    {
        "name": "Worry Time",
        "short_description": "Schedule specific time to worry",
        "detailed_instructions": "Set aside 15-20 minutes as your designated worry time. When worries arise outside this time, note them down and postpone them to your worry time. During worry time, actively think through your worries.",
        "duration_seconds": 900,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "CBT",
        "sub_category": "Worry Management",
        "target_emotions": ["anxiety", "worry", "rumination"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "CBT for Anxiety",
        "evidence_strength": "moderate"
    },
    {
        "name": "Decatastrophizing",
        "short_description": "Challenge worst-case scenario thinking",
        "detailed_instructions": "Ask yourself:\n1. What's the worst that could happen?\n2. What's the best that could happen?\n3. What's most likely to happen?\n4. If the worst happened, how would I cope?\n5. What would I tell a friend in this situation?",
        "duration_seconds": 480,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "CBT",
        "sub_category": "Cognitive Restructuring",
        "target_emotions": ["anxiety", "fear", "catastrophizing"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "CBT for Anxiety",
        "evidence_strength": "strong"
    },
    {
        "name": "Gratitude List",
        "short_description": "List 3 things you're grateful for",
        "detailed_instructions": "Write down 3 things you're grateful for today. They can be small (a warm cup of coffee) or big (supportive friends). For each one, write why you're grateful for it and how it makes you feel.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "CBT",
        "sub_category": "Positive Psychology",
        "target_emotions": ["negativity", "depression", "pessimism"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Positive Psychology Research",
        "evidence_strength": "strong"
    },

    # Mindfulness - 20 interventions
    {
        "name": "Body Scan",
        "short_description": "Systematically notice sensations in your body",
        "detailed_instructions": "Starting from your toes, slowly move your attention up through your body. Notice sensations without judging them. Spend 10-15 seconds on each area: toes, feet, ankles, calves, knees, thighs, hips, stomach, chest, hands, arms, shoulders, neck, face, head.",
        "duration_seconds": 600,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Body Awareness",
        "target_emotions": ["tension", "anxiety", "stress", "disconnection"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "MBSR Program",
        "evidence_strength": "strong"
    },
    {
        "name": "Mindful Breathing",
        "short_description": "Focus attention on the breath",
        "detailed_instructions": "Sit comfortably. Close your eyes or soften your gaze. Bring attention to your breath. Notice the sensation of breathing - the rise and fall, the temperature of air. When your mind wanders, gently return to the breath.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Attention Training",
        "target_emotions": ["anxiety", "stress", "restlessness", "overwhelm"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "MBSR Program",
        "evidence_strength": "strong"
    },
    {
        "name": "Loving-Kindness Meditation",
        "short_description": "Send compassionate wishes to yourself and others",
        "detailed_instructions": "Repeat these phrases:\n'May I be safe. May I be healthy. May I be happy. May I live with ease.'\nThen extend to someone you love, someone neutral, someone difficult, and all beings.",
        "duration_seconds": 600,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Compassion",
        "target_emotions": ["self_criticism", "anger", "loneliness", "resentment"],
        "adhd_friendly": False,
        "asd_friendly": False,
        "sensory_intensity": "low",
        "evidence_source": "Buddhist Psychology",
        "evidence_strength": "strong"
    },
    {
        "name": "Mindful Walking",
        "short_description": "Walk slowly with full attention",
        "detailed_instructions": "Walk slowly, paying attention to each step. Notice the lifting of your foot, moving forward, placing it down. Feel the ground beneath you. Notice your surroundings without judgment. Walk for 5-10 minutes.",
        "duration_seconds": 600,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Movement",
        "target_emotions": ["restlessness", "anxiety", "scattered", "stress"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "requires_movement": True,
        "evidence_source": "MBSR Program",
        "evidence_strength": "strong"
    },
    {
        "name": "RAIN Practice",
        "short_description": "Recognize, Allow, Investigate, Nurture",
        "detailed_instructions": "R - Recognize what is happening\nA - Allow the experience to be there\nI - Investigate with kindness (where do you feel it?)\nN - Nurture yourself with self-compassion\nSpend 1-2 minutes on each step.",
        "duration_seconds": 480,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Self-Compassion",
        "target_emotions": ["difficult_emotions", "self_criticism", "pain"],
        "adhd_friendly": False,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Tara Brach",
        "evidence_strength": "moderate"
    },
    {
        "name": "Counting Breaths",
        "short_description": "Count breaths 1-10, then repeat",
        "detailed_instructions": "Breathe naturally. Count 1 on inhale, 2 on exhale, 3 on next inhale, and so on up to 10. Then start over at 1. If you lose count, simply start again at 1. Practice for 3-5 minutes.",
        "duration_seconds": 300,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "Mindfulness",
        "sub_category": "Concentration",
        "target_emotions": ["scattered", "anxious", "overthinking"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Zen Practice",
        "evidence_strength": "moderate"
    },

    # Sensory Regulation - 15 interventions
    {
        "name": "Progressive Muscle Relaxation",
        "short_description": "Tense and release muscle groups",
        "detailed_instructions": "Systematically tense each muscle group for 5 seconds, then release for 10 seconds. Start with feet, then calves, thighs, buttocks, stomach, chest, hands, arms, shoulders, neck, and face. Notice the contrast between tension and relaxation.",
        "duration_seconds": 900,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "Sensory",
        "sub_category": "Muscle Relaxation",
        "target_emotions": ["tension", "anxiety", "stress", "physical_discomfort"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "Jacobson PMR",
        "evidence_strength": "strong"
    },
    {
        "name": "Weighted Blanket Break",
        "short_description": "Use deep pressure for calming",
        "detailed_instructions": "Wrap yourself in a weighted blanket or heavy blanket. The deep pressure stimulates your proprioceptive system and can help calm your nervous system. Rest for 10-15 minutes.",
        "duration_seconds": 900,
        "effort_level": "minimal",
        "energy_required": "minimal",
        "therapeutic_approach": "Sensory",
        "sub_category": "Deep Pressure",
        "target_emotions": ["anxiety", "overwhelm", "sensory_overload", "restlessness"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "Occupational Therapy",
        "evidence_strength": "moderate"
    },
    {
        "name": "Noise-Canceling Break",
        "short_description": "Silent headphone break for auditory reset",
        "detailed_instructions": "Put on noise-canceling headphones without any audio. Just silence. Find a quiet spot and sit or lie down. Let your auditory system rest. Stay like this for 5-10 minutes.",
        "duration_seconds": 600,
        "effort_level": "minimal",
        "energy_required": "minimal",
        "therapeutic_approach": "Sensory",
        "sub_category": "Auditory Regulation",
        "target_emotions": ["sensory_overload", "overwhelm", "irritability"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Sensory Processing Research",
        "evidence_strength": "moderate"
    },
    {
        "name": "Aromatherapy Reset",
        "short_description": "Use scent for emotional regulation",
        "detailed_instructions": "Choose a calming scent: lavender for relaxation, peppermint for alertness, or citrus for mood boost. Inhale deeply 3-5 times. Focus on the scent and how it makes you feel. Use essential oil, lotion, or natural source.",
        "duration_seconds": 180,
        "effort_level": "minimal",
        "energy_required": "minimal",
        "therapeutic_approach": "Sensory",
        "sub_category": "Olfactory",
        "target_emotions": ["anxiety", "stress", "low_mood", "nausea"],
        "adhd_friendly": True,
        "asd_friendly": False,
        "sensory_intensity": "moderate",
        "evidence_source": "Aromatherapy Research",
        "evidence_strength": "moderate"
    },
    {
        "name": "Fidget Tool Use",
        "short_description": "Use tactile stimulation for focus",
        "detailed_instructions": "Use a fidget toy, stress ball, or textured object. Focus on the sensation in your hands while your mind works through difficult thoughts or emotions. This can help with both focus and emotional regulation.",
        "duration_seconds": 300,
        "effort_level": "minimal",
        "energy_required": "minimal",
        "therapeutic_approach": "Sensory",
        "sub_category": "Tactile",
        "target_emotions": ["restlessness", "anxiety", "unfocused", "stress"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "ADHD Research",
        "evidence_strength": "moderate"
    },
    {
        "name": "Cold Water Face Splash",
        "short_description": "Splash cold water on face to reset",
        "detailed_instructions": "Fill a basin with cold water or use running cold water. Splash your face several times, focusing on forehead and cheeks. The cold stimulates your dive reflex and can quickly shift your emotional state.",
        "duration_seconds": 60,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "Sensory",
        "sub_category": "Temperature",
        "target_emotions": ["panic", "dissociation", "intense_emotion"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "evidence_source": "DBT/Sensory Integration",
        "evidence_strength": "strong"
    },

    # Physical/Movement - 15 interventions
    {
        "name": "Shake It Off",
        "short_description": "Shake your whole body to release tension",
        "detailed_instructions": "Stand with feet hip-width apart. Start shaking your hands, then arms, shoulders, whole body. Shake vigorously for 1-2 minutes. Let your body move naturally. Shake out stress and tension.",
        "duration_seconds": 180,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "Physical",
        "sub_category": "Tension Release",
        "target_emotions": ["tension", "anxiety", "stress", "restlessness"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "requires_movement": True,
        "evidence_source": "TRE/Somatic",
        "evidence_strength": "moderate"
    },
    {
        "name": "Power Pose",
        "short_description": "Stand in confident posture",
        "detailed_instructions": "Stand tall with feet wide, hands on hips (Wonder Woman pose) or arms raised in V shape. Take up space. Hold for 2 minutes. This can increase confidence hormones and decrease stress hormones.",
        "duration_seconds": 120,
        "effort_level": "low",
        "energy_required": "low",
        "therapeutic_approach": "Physical",
        "sub_category": "Body Language",
        "target_emotions": ["low_confidence", "anxiety", "powerlessness"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "requires_movement": True,
        "evidence_source": "Amy Cuddy Research",
        "evidence_strength": "moderate"
    },
    {
        "name": "Yoga Stretch Sequence",
        "short_description": "Simple yoga poses for tension release",
        "detailed_instructions": "Do these poses, holding each for 30 seconds:\n1. Child's pose\n2. Cat-cow stretches\n3. Downward dog\n4. Standing forward fold\n5. Mountain pose with arms raised\nBreathe deeply throughout.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "low",
        "therapeutic_approach": "Physical",
        "sub_category": "Yoga",
        "target_emotions": ["tension", "stress", "anxiety", "stiffness"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "requires_movement": True,
        "evidence_source": "Yoga Research",
        "evidence_strength": "strong"
    },
    {
        "name": "Wall Push-Ups",
        "short_description": "Quick resistance exercise for energy shift",
        "detailed_instructions": "Stand arm's length from a wall. Place palms flat against the wall. Do 10-15 push-ups against the wall. The resistance helps release tension and can shift your energy and mood.",
        "duration_seconds": 120,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "Physical",
        "sub_category": "Resistance",
        "target_emotions": ["anger", "frustration", "restlessness", "low_energy"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "moderate",
        "requires_movement": True,
        "evidence_source": "Exercise Psychology",
        "evidence_strength": "strong"
    },
    {
        "name": "Butterfly Hug",
        "short_description": "Self-hug with bilateral stimulation",
        "detailed_instructions": "Cross your arms over your chest, hands resting on opposite shoulders. Alternately tap your shoulders left-right-left-right in a slow, steady rhythm. Continue for 2-3 minutes while breathing deeply.",
        "duration_seconds": 180,
        "effort_level": "low",
        "energy_required": "minimal",
        "therapeutic_approach": "Physical",
        "sub_category": "Self-Soothing",
        "target_emotions": ["anxiety", "distress", "loneliness", "fear"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "EMDR/Trauma Therapy",
        "evidence_strength": "moderate"
    },
    {
        "name": "Dance Break",
        "short_description": "Move your body freely to music",
        "detailed_instructions": "Put on music you enjoy. Dance freely without judgment. Move however your body wants to move. Let the rhythm guide you. Dance for 3-5 minutes. Let emotions move through you.",
        "duration_seconds": 300,
        "effort_level": "medium",
        "energy_required": "medium",
        "therapeutic_approach": "Physical",
        "sub_category": "Movement",
        "target_emotions": ["low_mood", "stuck", "restless", "boredom"],
        "adhd_friendly": True,
        "asd_friendly": False,
        "sensory_intensity": "high",
        "requires_movement": True,
        "evidence_source": "Dance/Movement Therapy",
        "evidence_strength": "moderate"
    },
    {
        "name": "Grounding Through Feet",
        "short_description": "Connect with ground through your feet",
        "detailed_instructions": "Stand or sit with feet flat on the floor. Press your feet firmly down. Notice the connection with the ground. Imagine roots growing from your feet into the earth. Feel stable and supported.",
        "duration_seconds": 180,
        "effort_level": "minimal",
        "energy_required": "minimal",
        "therapeutic_approach": "Physical",
        "sub_category": "Grounding",
        "target_emotions": ["anxiety", "dissociation", "ungrounded", "panic"],
        "adhd_friendly": True,
        "asd_friendly": True,
        "sensory_intensity": "low",
        "evidence_source": "Somatic Therapy",
        "evidence_strength": "moderate"
    },
]

def seed_database():
    """Seed the database with interventions"""
    db = SessionLocal()
    try:
        # Check if already seeded
        existing_count = db.query(Intervention).count()
        if existing_count > 0:
            print(f"Database already has {existing_count} interventions. Skipping seed.")
            return

        # Add all interventions
        for intervention_data in INTERVENTIONS:
            intervention = Intervention(**intervention_data)
            db.add(intervention)

        db.commit()
        print(f"Successfully seeded {len(INTERVENTIONS)} interventions!")

    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
